name: CI Pipeline Run Project

on:
  push:
    branches: [ juan-cano ]
  pull_request:
    branches: [ juan-cano ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Run API (smoke test)
      run: |
       # Start server in background
        npm run start:prod &
        
        # Wait for server to start
        sleep 15
        
        # Check health endpoint
        curl -v http://localhost:3000/api/health
        
        # Verify server process is running
        ps aux | grep node
        
        # If health check fails, exit with error
        if ! curl -s -f http://localhost:3000/api/health > /dev/null; then
          echo "Health check failed"
          exit 1
        fi

    - name: Stop server
      if: always()
      run: pkill -f "node dist/src/main" || true